"""Tests for fragmentomics_tools.dataframe.RegionDataFrame.

Triage (2026-09-24) classified the original 23 tests, none of which had run
since the S3 bucket s3://test-data-manifest-2-2024 was decommissioned.  The
module could not even collect: a fixture read sat in a *default argument*,
which is evaluated at def time and so touched disk at import.

Restored (8 tests): use a synthetic TSS fixture generated by
    test/generate_tss_fixture.py with deterministic construction.  Assertions
    are derived from the construction parameters, not memorised constants.

Deleted (15 tests): 10 were dead code that never ran -- they depended on an
    ``sdf`` fixture whose body was ``assert False``, called library methods
    that no longer exist (build_sample_region_dataframe,
    _get_fragment_h5_paths), or referenced undefined names (blacklist_path,
    REPO_DATA_DIR, SAMPLE_DF); two of those were also exact duplicates.  The
    remaining 5 were assertion-hollow: they pinned real ENCODE/CTCF/bigwig
    values that are unrecoverable, so synthesising a fixture would have reduced
    each assertion to "the code produces what it currently produces".  Deleted
    by owner decision rather than kept as permanent skips.  See git log for
    per-test justification.

Library defect found during triage (reported, now fixed):
    ``intersect_with_rdf`` did not return geometric intersections — it returned
    whole A intervals joined on overlap.  It has been renamed to
    ``join_on_overlap`` to reflect its actual behaviour; the old name raises
    AttributeError.  test_intersect_region_dataframe below asserts current
    behaviour via the new name.
"""
import tempfile

import pandas as pd
import pytest
from pathlib import Path

from fragmentomics_tools.dataframe import (
    RegionDataFrame,
    intersect_region_dataframes,
)
from fragmentomics_tools.region import Region


# ── Fixture paths ────────────────────────────────────────────────────────
TEST_DATA_DIR = Path(__file__).parent / "data"
TSS_ANNOTATION_FILE = str(TEST_DATA_DIR / "tss.synthetic.hg19.bed.gz")

# ── Construction constants (must match test/generate_tss_fixture.py) ─────
TSS_TOTAL_ROWS = 200
TSS_ROWS_PER_CHROM = {
    "chr1": 50, "chr2": 40, "chr3": 30, "chr4": 20,
    "chr5": 15, "chr6": 10, "chr7": 10, "chrX": 25,
}
# peak_tpm for row i (0-indexed) = (i + 1) * 0.25;  range [0.25, 50.0]
# peak_tpm > 10  ⇔  (i+1)*0.25 > 10  ⇔  i ≥ 40  →  200 − 40 = 160 rows
TSS_N_PEAK_TPM_ABOVE_10 = 160


# ═══════════════════════════════════════════════════════════════════════
# Bucket 1 — restored tests with real invariant assertions
# ═══════════════════════════════════════════════════════════════════════

def test_load_region_data_frame():
    """Load synthetic TSS via pd.read_table; row count matches construction."""
    rdf = RegionDataFrame(pd.read_table(TSS_ANNOTATION_FILE), ref="hg19")
    assert len(rdf) == TSS_TOTAL_ROWS


def test_load_from_fname_s3_or_local():
    """Same fixture via from_fname_s3_or_local (exercises BedReader path)."""
    rdf = RegionDataFrame.from_fname_s3_or_local(TSS_ANNOTATION_FILE, ref="hg19")
    assert len(rdf) == TSS_TOTAL_ROWS


def test_filter_peak_tpm():
    """peak_tpm > 10 filter count matches analytical expectation."""
    rdf = RegionDataFrame(pd.read_table(TSS_ANNOTATION_FILE), ref="hg19")
    res = rdf.query("peak_tpm > 10")
    assert len(res) == TSS_N_PEAK_TPM_ABOVE_10


def test_split_on_contig():
    """Per-chromosome counts after split match the fixture's known layout."""
    rdf = RegionDataFrame(pd.read_table(TSS_ANNOTATION_FILE), ref="hg19")

    d1, d2, d3 = rdf.split_on_contig(["chr1", "chr2", ["chr3", "chr4"]])
    assert d1.shape[0] == TSS_ROWS_PER_CHROM["chr1"]
    assert d2.shape[0] == TSS_ROWS_PER_CHROM["chr2"]
    assert d3.shape[0] == TSS_ROWS_PER_CHROM["chr3"] + TSS_ROWS_PER_CHROM["chr4"]

    with pytest.raises(ValueError):
        rdf.split_on_contig([["chr1", "chr2"], ["chr2", "chr3"]])


def test_intersect_region_dataframe():
    """Intersection of two synthetic RDFs returns expected overlapping regions.

    NOTE: join_on_overlap defaults to wa=True, wb=True (bedtools -wa -wb),
    so it returns whole A intervals that overlap B rather than the geometric
    intersection.  This test asserts that behaviour.
    """
    rdf_1 = RegionDataFrame.from_regions(
        [Region("chr1", 1000, 1500), Region("chr1", 2000, 2100)], ref="hg19"
    )
    rdf_2 = RegionDataFrame.from_regions(
        [Region("chr1", 1300, 2100), Region("chr3", 4000, 4100)], ref="hg19"
    )

    intersection_rdf = intersect_region_dataframes([rdf_1, rdf_2])
    assert isinstance(intersection_rdf, RegionDataFrame)
    intersection_regions = list(intersection_rdf.iter_regions())
    # With wa=True, whole A intervals are returned (not geometric clips):
    assert intersection_regions[0] == Region("chr1", 1000, 1500, ref="hg19")
    assert intersection_regions[1] == Region("chr1", 2000, 2100, ref="hg19")

    # The two entry-points agree with each other.
    for region_1, region_2 in zip(
        rdf_1.join_on_overlap(rdf_2).iter_regions(),
        intersect_region_dataframes([rdf_1, rdf_2]).iter_regions(),
    ):
        assert region_1 == region_2, f"{region_1}, {region_2}"


def test_lift_over_no_id_column():
    """Liftover of identity-mapped chr1 regions preserves all values."""
    rdf = RegionDataFrame.from_regions(
        [Region("chr1", 1000 + i * 500, 1500 + i * 500) for i in range(20, 100)],
        ref="hg19",
    )
    rdf_lift_over = rdf.lift_over("hg38", transfer_columns=True)
    assert (rdf.values == rdf_lift_over.values).all()


def test_to_tsv():
    """Round-trip through to_tsv preserves columns and shape."""
    rdf = RegionDataFrame.from_regions(
        [Region("chr1", 1000 + i * 500, 1500 + i * 500) for i in range(10)],
        ref="hg19",
    )
    with tempfile.TemporaryDirectory() as tmp_dir:
        rdf.to_tsv(f"{tmp_dir}/tmp.tsv")
        rdf_r = pd.read_csv(f"{tmp_dir}/tmp.tsv", sep="\t")

    assert (rdf.columns == rdf_r.columns).all()
    assert rdf.shape == rdf_r.shape


def test_rdfs_equal():
    """Equality and inequality of RDFs from known regions."""
    regions_a = [Region("chr1", 1000 + i * 500, 1500 + i * 500) for i in range(5)]
    regions_b = [Region("chr1", 1000 + i * 500, 1500 + i * 500) for i in range(10)]
    regions_c = [Region("chr1", 1000 + i * 500, 1500 + i * 500) for i in range(5, 10)]

    rdf = RegionDataFrame.from_regions(regions_a, ref="hg19")
    rdf_same = RegionDataFrame.from_regions(regions_a, ref="hg19")
    rdf_different_1 = RegionDataFrame.from_regions(regions_b, ref="hg19")
    rdf_different_2 = RegionDataFrame.from_regions(regions_c, ref="hg19")

    assert rdf.equals(rdf_same)
    assert not rdf.equals(rdf_different_1)
    assert not rdf.equals(rdf_different_2)
